apiVersion: v1
kind: Pod
metadata:
  name: dev-pod
  namespace: development
spec:
  serviceAccountName: dev-team
  containers:
  - name: kubectl-container
    image: bitnami/kubectl:latest
    command: ["sleep", "3600"]
  restartPolicy: Never
