apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: readonly-binding
  namespace: testing
subjects:
- kind: ServiceAccount
  name: readonly-user
  namespace: testing
roleRef:
  kind: Role
  name: readonly-access
  apiGroup: rbac.authorization.k8s.io
